# Generated by Django 3.1.7 on 2021-08-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('Bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bus_number', models.CharField(max_length=20, unique=True)),
                ('Bus_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'buses',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('Driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('Driver_name', models.CharField(max_length=100)),
                ('Driver_phone', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'drivers',
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('Route_id', models.AutoField(primary_key=True, serialize=False)),
                ('Route_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('Location_id', models.AutoField(primary_key=True, serialize=False)),
                ('Lat', models.CharField(max_length=50)),
                ('Long', models.CharField(max_length=50)),
                ('Bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buses')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='BusRouteTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timing', models.TimeField()),
                ('Bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buses')),
                ('Route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routes')),
            ],
            options={
                'db_table': 'bus_route_timing',
            },
        ),
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buses')),
                ('Driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
            options={
                'db_table': 'bus_driver',
            },
        ),
    ]
